server:
  port: 12000

spring:
  application:
    name: url-shortener
  datasource:
    url: jdbc:mysql://localhost:3306/url_shortener?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 'root'
    password: 'root'

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

app:
  base62:
    chars: '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
  shortcode:
    length: 6
  max:
    retries: 5

# CORS Configuration
cors:
  allowed-origins: http://localhost:5173,http://localhost:3000